import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col w-vw h-svh bg-black text-white`}>
        <Navbar />
        <Toaster 
          position="top-right"
          toastOptions={{
            style: {
              background: "#000",
              color: "#fff",
              border: "1px solid #525252",
            },
          }}
        />
        <main className="flex flex-col items-center gap-8 p-2 md:p-4 h-full">
          <div className="flex-1 w-full rounded relative">
            <div className="w-full box-border mx-auto px-4">
              {children}
            </div>
          </div>
        </main>
      </body>
    </html>
  );
}
